name: SinkPetitions
version: ${project.version}
description: A plugin that provides a petition (ticket) management system.
author: Shadow1Raven
main: de.static_interface.sinkpetitions.SinkPetitions
depend: [SinkLibrary]
